name: Model

on:
  push:
    branches: [master]
    paths:
      - 'model/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./model
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
    - name: Lint with flake8
      run: |
        conda install -c conda-forge flake8-black
        flake8 .
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: |
        pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
        mkdir empty
        python test_handler_unit.py
      working-directory: ${{env.working-directory}}