name: Website

on:
  push:
    branches: [master]
    paths:
      - 'website/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./website
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: |
        chmod +x prettier.sh
        ./prettier.sh --check
        npm run lint .
      working-directory: ${{env.working-directory}}
      
